Added data dictionary for 009-128 model air conditioner
oyvindwe/connectlife-ha pull request #110
Opened 2024-08-17 13:22 UTC by psycho202

Added my model of AC. Seems similar to existing model 09-100, so copied but adjusted presets for my own use case. 

Further improvements to data_dictionary for this model and possibly others: 
- property f_votage corresponds to grid voltage, as measured by the indoor unit. 
Couldn't get this to work to add it as a property with the correct sensor device class. 

- property f_cool_qvalue corresponds to the BTU/hr of the unit, how much heat it's removing at that moment. Cool data to know how "hard" the aircon is working at a certain point in time.

- property t_fan_speed_s remains equal to t_fan_speed, so this property can probably be disabled by default?

2024-08-17 13:31 UTC, psycho202 commented
![image](https://github.com/user-attachments/assets/99131f40-1a95-4bfd-a052-b6edbd42b70d)
Example of f_cool_qvalue values in HA for this model

2024-08-18 15:55 UTC, oyvindwe commented
Thank you for your contribution! ❤️ 

> property f_votage corresponds to grid voltage, as measured by the indoor unit.
> Couldn't get this to work to add it as a property with the correct sensor device class.
`f_votage` or `f_voltage`? Spelling errors seem to be quite common in this API. Probably not very useful, but did you try this:
```
- property: f_votage
  sensor:
    device_class: voltage
    unit: V
```

> property f_cool_qvalue corresponds to the BTU/hr of the unit, how much heat it's removing at that moment. Cool data to know how "hard" the aircon is working at a certain point in time.

I don't see any matching device class, but this should work:
```
- property: f_cool_qvalue
  sensor:
    unit: BTU/hr
    state_class: measurement
```

> property t_fan_speed_s remains equal to t_fan_speed, so this property can probably be disabled by default?

Unmapped properties are hidden by default. Currently no support to disable properties completely, but that may be a nice feature to add.

2024-08-18 16:18 UTC, psycho202 commented
Thanks @oyvindwe, tested and added the properties!

f_votage indeed is a typo in the API. Also added the f_heat_qvalue, some icons and their text mapping to the strings.json and en.json files.

2024-08-18 16:28 UTC, oyvindwe requested changes
Looks good! Only thing is that it should not be necessary to include the unit in the property strings.

Preferred SI abbreviation for hours is h (apologies for not stating this in previous comment).

2024-08-18 16:28 UTC, oyvindwe commented on custom_components/connectlife/strings.json
> +        "name": "BTU/Hr Heating"
```
        "name": "Heating"
```

2024-08-18 16:28 UTC, oyvindwe commented on custom_components/connectlife/strings.json
> +        "name": "BTU/Hr Cooling"
```
        "name": "Cooling"
```

2024-08-18 16:28 UTC, oyvindwe commented on custom_components/connectlife/strings.json
> +        "name": "Measured Grid Voltage"
```
        "name": "Measured grid voltage"
```

2024-08-18 16:28 UTC, oyvindwe commented on custom_components/connectlife/translations/en.json
> +              "name": "BTU/Hr Heating"
```
        "name": "Heating"
```

2024-08-18 16:28 UTC, oyvindwe commented on custom_components/connectlife/translations/en.json
> +              "name": "BTU/Hr Cooling"
```
        "name": "Cooling"
```

2024-08-18 16:28 UTC, oyvindwe commented on custom_components/connectlife/translations/en.json
> +              "name": "Measured Grid Voltage"
```
        "name": "Measured grid voltage"
```

2024-08-18 16:28 UTC, oyvindwe commented on custom_components/connectlife/data_dictionaries/009-128.yaml
> +      unit: BTU/hr
```
      unit: BTU/h
```

2024-08-18 16:28 UTC, oyvindwe commented on custom_components/connectlife/data_dictionaries/009-128.yaml
> +      unit: BTU/hr
```
      unit: BTU/h
```

2024-08-20 16:44 UTC, oyvindwe approved these changes
I committed the requested changes.

2024-08-20 16:45 UTC, merged

2024-08-20 16:46 UTC, oyvindwe commented
Tip for future PRs: Make a _branch_ in your forks before committing changes, so you can keep main in sync with upstream repo.

2024-08-20 16:53 UTC, psycho202 commented
> Tip for future PRs: Make a _branch_ in your forks before committing changes, so you can keep `main` in sync with upstream repo.

Thanks for the tip! I'm not a developer by trade, so I'm not very used to working with github :)
Trying my best though!