030-1wk100028v0w (Hisense DH5S102BW tumble dryer)
oyvindwe/connectlife-ha pull request #120
Opened 2024-08-23 08:53 UTC by gregrs-uk

Started mapping Hisense DH5S102BW tumble dryer

2024-08-24 15:05 UTC, oyvindwe requested changes
Thank your for your contribution! ❤️

I added some comments even though you set it as a draft.

2024-08-24 15:05 UTC, oyvindwe commented on custom_components/connectlife/data_dictionaries/030-1wk100028v0w.yaml
> +    select:
This can be simplified to `switch: {}` without `options` (0 defaults to off and 1 defaults to on).

2024-08-24 15:05 UTC, oyvindwe commented on custom_components/connectlife/data_dictionaries/030-1wk100028v0w.yaml
> +    select:
This can also be simplified to `switch: {}`

2024-08-24 15:05 UTC, oyvindwe commented on custom_components/connectlife/strings.json
> +      "Drum_Light": {
Simplify and move to `"switch"` section

2024-08-24 15:05 UTC, oyvindwe commented on custom_components/connectlife/strings.json
> +      "Child_lock": {
Move to `"switch"` section and remove `"state"` (and remember to update `en.json` as well).

2024-10-21 10:46 UTC, gregrs-uk commented
I still need to work out the values for `Current_program_phase` but @oyvindwe would you mind taking a look at my latest commits?

2024-10-21 11:09 UTC, oyvindwe commented
@gregrs-uk Looks good to me so far!

2024-10-21 12:43 UTC, gregrs-uk commented
@oyvindwe There are other properties available but I've defined the most useful ones so I think that's as far as I'm likely to go. Would you mind checking and merging if you're happy?

2024-10-21 12:47 UTC, gregrs-uk commented
Sorry, just spotted an error from when I merged the main branch into this feature branch. Will fix…

2024-10-21 19:36 UTC, gregrs-uk commented
@oyvindwe Should be good to go now. I've rebased on main so should be easy to merge.

2024-10-21 20:10 UTC, gregrs-uk commented
Any idea why properties aren't picking up the names I've given them in `strings.json` and `en.json`? For example 'AntiCrease' should be 'Anti crease'. (Others have the wrong capitalisation.)

<img width="441" alt="Screenshot 2024-10-21 at 21 09 12" src="https://github.com/user-attachments/assets/21146806-0622-41ef-84dc-0d3bdc78ed93">

2024-10-22 05:15 UTC, oyvindwe commented
> Any idea why properties aren't picking up the names I've given them in `strings.json` and `en.json`?

In `strings.json` and `en.json`, the keys must be in lowercase, while the mapping file uses the casing from the API. This was introduced in https://github.com/oyvindwe/connectlife-ha/pull/138

It's stated in the doc, but a bit hidden:
https://github.com/oyvindwe/connectlife-ha/tree/main/custom_components/connectlife/data_dictionaries#mapping-tips-and-tricks

2024-10-22 05:19 UTC, oyvindwe commented
If you use the `python -m scripts.gen_strings` script, it should generate the missing keys.

2024-10-22 12:51 UTC, gregrs-uk commented
Thanks. I will fix that. I didn't see `python -m connectlife.dump --username <username> --password <password> --format dd` in the docs originally so not all the properties are included in my mapping, only the ones I've defined. Would you like the properties I haven't defined to be included (but hidden)?

2024-10-22 19:05 UTC, gregrs-uk commented
Hopefully ready to merge now

2024-10-22 20:48 UTC, oyvindwe commented on custom_components/connectlife/translations/en.json
> +            "Dry_Level": {
Great work! You missed this one though.

2024-10-22 21:05 UTC, oyvindwe commented
Thanks! I fixed the remaining issues with the translation keys.

2024-10-22 21:05 UTC, oyvindwe approved these changes

2024-10-22 21:06 UTC, merged