Add support for air conditioner AP10TW1RLR-N 006-200
oyvindwe/connectlife-ha pull request #97
Opened 2024-08-07 13:15 UTC by jonchampagne

Been using this dictionary config for a week or so and it seems to be accurate.

2024-08-07 19:01 UTC, oyvindwe requested changes
Thank your very much for your contribution ❤️ 

I left one comment.

2024-08-07 19:01 UTC, oyvindwe commented on custom_components/connectlife/data_dictionaries/006-200.yaml
> +- property: f_temp_in
This seems to be the current temperatur on other A/C units at least. Can you test this mapping?
```
- property: f_temp_in
  climate:
    target: current_temperature
```

2024-08-07 22:40 UTC, jonchampagne commented on custom_components/connectlife/data_dictionaries/006-200.yaml
> +- property: f_temp_in
Thanks,

I don't think this is the current temperature, or at least if it is than it's an inaccurate reading. 
Comparing it with a climate sensor both in the same room and on my balcony, this seems to much more align with the outdoor temperature than the indoor one. I'm not sure though whether this is just down to where the temperature probe is placed within the AC unit or not. 

![image](https://github.com/user-attachments/assets/de86669f-2b93-436e-b93c-87c5c8ea12b2)

2024-08-08 10:37 UTC, oyvindwe commented on custom_components/connectlife/data_dictionaries/006-200.yaml
> +- property: f_temp_in
I see. We should just make a separate sensor of it with `device_class: temperature`. Note that you have to hard code either `F` or `C` as unit. I'll make a separate issue to support setting unit based on another property (as is done for the `climate` entity).

2024-08-08 18:00 UTC, oyvindwe requested changes

2024-08-08 18:00 UTC, oyvindwe commented on custom_components/connectlife/data_dictionaries/006-200.yaml
> +  device_class: temperature
Needs to be:
```
  sensor:
    device_class: temperature
    unit: °C # or °F
```
Maybe best to just leave without mapping until issue #100 is fixed

2024-08-10 02:13 UTC, smaddock commented
Interesting, I had just duplicated the 006-201 data dictionary for my 006-200 (almost identical to the one here) which also has f_temp_in mapped as a property, and my only complaint was I couldn’t reference it in sensor cards.

2024-08-10 17:43 UTC, smaddock commented
Okay to my previous comment, I set `f_temp_in` as:
```yaml
- property: f_temp_in
  icon: mdi:temp
  climate:
    target: current_temperature
```
And then created a sensor template helper to get me the sensor data I wanted:
```jinja
{{ state_attr("climate.portable_air_conditioner", "current_temperature") }}
```

2024-08-10 18:00 UTC, smaddock commented
A few other notes testing your config @jonchampagne:

- `daily_energy_kwh` is always zero on my model, so I'd removed it
- `t_eco` does nothing on my model, I try setting it but the API keeps returning zero, so I'd removed it
- It looks like you're specifying non-core icons for `t_sleep` and `t_super`; you might want to change those to `mdi:power-sleep` and `mdi:fast-forward` respectively just for compatibility
- I'll submit a separate PR to get the Sleep switch added to the i18n options
- `t_fan_mute` is valid on my model, however it is redundant with the built-in "Disable beep" option when you configure a device with this integration, so probably only worth adding if you enable and disable the beep often. If you want to add, it can be set as:
```yaml
- property: t_fan_mute
  icon: mdi:volume-variant-off
  switch:
    device_class: switch
```

2024-08-17 02:26 UTC, smaddock commented
@jonchampagne if you can’t or don’t want to make these changes I can submit a new PR as it looks like @Go2Engle also has this model, but I’d rather you get the credit for being the first to submit.

2024-08-21 06:04 UTC, oyvindwe commented
Superseeded by #105 

I'll make sure to credit both of you as well in the release notes, @jonchampagne and @smaddock :)

2024-08-21 06:04 UTC, closed without merging